import type { Match } from "./schema";

const syncedAt = "2026-07-09T09:00:00.000Z";

export const lolMockMatches: Match[] = [
  {
    id: "mock-lol-lpl-blg-tes-20260710",
    game: "lol",
    gameName: "League of Legends",
    league: "LPL",
    tournament: "LPL Summer 2026",
    stage: "Regular Season",
    teamA: "BLG",
    teamB: "TES",
    startTime: "2026-07-10T11:00:00.000Z",
    endTime: "2026-07-10T13:30:00.000Z",
    format: "BO3",
    status: "scheduled",
    source: "mock:lol",
    sourceUrl: "https://example.com/lol/lpl/blg-vs-tes",
    streamUrl: "https://live.example.com/lpl",
    summary: "LPL 焦点战，BLG 与 TES 的强强对话，关注中野节奏。",
    lastSyncedAt: syncedAt,
  },
  {
    id: "mock-lol-lck-t1-gen-20260711",
    game: "lol",
    gameName: "League of Legends",
    league: "LCK",
    tournament: "LCK Summer 2026",
    stage: "Regular Season",
    teamA: "T1",
    teamB: "GEN",
    startTime: "2026-07-11T08:00:00.000Z",
    format: "BO3",
    status: "scheduled",
    source: "mock:lol",
    sourceUrl: "https://example.com/lol/lck/t1-vs-gen",
    streamUrl: "https://live.example.com/lck",
    summary: "LCK 高关注度对局，T1 与 GEN 的运营细节值得留意。",
    lastSyncedAt: syncedAt,
  },
  {
    id: "mock-lol-worlds-edg-drx-20261018",
    game: "lol",
    gameName: "League of Legends",
    league: "Worlds",
    tournament: "World Championship 2026",
    stage: "Swiss Stage",
    teamA: "EDG",
    teamB: "DRX",
    startTime: "2026-10-18T12:00:00.000Z",
    format: "BO5",
    status: "scheduled",
    source: "mock:lol",
    sourceUrl: "https://example.com/lol/worlds/edg-vs-drx",
    streamUrl: "https://live.example.com/worlds",
    summary: "全球总决赛舞台再遇老对手，重点关注团战决策。",
    lastSyncedAt: syncedAt,
  },
];

export const valorantMockMatches: Match[] = [
  {
    id: "mock-valorant-vct-cn-edg-wolves-20260712",
    game: "valorant",
    gameName: "VALORANT",
    league: "VCT CN",
    tournament: "VCT CN Stage 2 2026",
    stage: "Playoffs",
    teamA: "EDG",
    teamB: "Wolves",
    startTime: "2026-07-12T10:00:00.000Z",
    format: "BO3",
    status: "scheduled",
    source: "mock:valorant",
    sourceUrl: "https://example.com/valorant/vct-cn/edg-vs-wolves",
    streamUrl: "https://live.example.com/vct-cn",
    summary: "VCT CN 淘汰赛关键战，关注进攻方节奏与残局处理。",
    lastSyncedAt: syncedAt,
  },
  {
    id: "mock-valorant-vct-pacific-prx-drx-20260713",
    game: "valorant",
    gameName: "VALORANT",
    league: "VCT Pacific",
    tournament: "VCT Pacific Stage 2 2026",
    stage: "Group Stage",
    teamA: "PRX",
    teamB: "DRX",
    startTime: "2026-07-13T09:00:00.000Z",
    endTime: "2026-07-13T11:30:00.000Z",
    format: "BO3",
    status: "scheduled",
    source: "mock:valorant",
    sourceUrl: "https://example.com/valorant/vct-pacific/prx-vs-drx",
    streamUrl: "https://live.example.com/vct-pacific",
    summary: "太平洋赛区节奏对撞，PRX 与 DRX 的地图选择值得关注。",
    lastSyncedAt: syncedAt,
  },
  {
    id: "mock-valorant-masters-sentinels-fnatic-20260802",
    game: "valorant",
    gameName: "VALORANT",
    league: "VCT Masters",
    tournament: "VCT Masters 2026",
    stage: "Upper Bracket",
    teamA: "Sentinels",
    teamB: "FNATIC",
    startTime: "2026-08-02T13:00:00.000Z",
    format: "BO5",
    status: "scheduled",
    source: "mock:valorant",
    sourceUrl: "https://example.com/valorant/masters/sen-vs-fnc",
    streamUrl: "https://live.example.com/masters",
    summary: "国际赛强强对话，重点关注地图池与关键枪位博弈。",
    lastSyncedAt: syncedAt,
  },
];

export const allMockMatches = [...lolMockMatches, ...valorantMockMatches];
