import { Match } from "../connectors/types";

/**
 * Mock 数据
 * 基于 2026年7月真实电竞赛事日历构造
 * 当真实 API (LoL Esports / VLR.gg) 不可达时作为 fallback
 *
 * 2026年7月实际情况（截至 7月13日）：
 * - MSI 2026 昨天(7月12日)结束: HLE vs BLG 总决赛
 * - LPL Split 3 (登峰/涅槃组内赛): 7月22日开始，BO3，五城巡回
 *   - 登峰组: AL, BLG, EDG, JDG, LGD, TES, TT, WE
 *   - 涅槃组: iG, LNG, NIP, WBG
 * - KeSPA Cup 2026: 7月20日-8月18日
 * - LCK Summer 后半段: 7月29日恢复 (3-4轮)
 *   - Legend组: HLE, T1, GEN, KT, DK
 *   - Rise组: BRO, BFX, DRX, NS, DNS
 * - LEC Playoffs: 7月22-28日
 * - LCS Summer: 7月27-28日有比赛
 */

function futureDate(daysAhead: number, hours: number = 17): string {
  const d = new Date();
  d.setDate(d.getDate() + daysAhead);
  d.setHours(hours, 0, 0, 0);
  return d.toISOString();
}

function pastDate(daysAgo: number): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
}

export const mockLoLMatches: Match[] = [
  // === MSI 2026 (已结束，历史参考) ===
  {
    id: "lol-mock-msi-final",
    game: "lol",
    gameName: "英雄联盟",
    league: "MSI",
    tournament: "MSI 2026",
    stage: "Grand Final",
    teamA: "HLE",
    teamB: "BLG",
    startTime: pastDate(1),
    format: "BO5",
    status: "finished",
    source: "mock",
    summary: "MSI 2026总决赛，HLE 3-1 BLG夺得MSI冠军。",
    lastSyncedAt: new Date().toISOString(),
  },
  // === KeSPA Cup 2026 (7月20日开始) ===
  {
    id: "lol-mock-kespa-001",
    game: "lol",
    gameName: "英雄联盟",
    league: "LCK",
    tournament: "KeSPA Cup 2026",
    stage: "小组赛 A组",
    teamA: "T1",
    teamB: "GEN",
    startTime: futureDate(7, 16),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "2026 KeSPA Cup揭幕战，T1对阵GEN。",
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "lol-mock-kespa-002",
    game: "lol",
    gameName: "英雄联盟",
    league: "LCK",
    tournament: "KeSPA Cup 2026",
    stage: "小组赛 A组",
    teamA: "HLE",
    teamB: "DK",
    startTime: futureDate(8, 16),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "HLE vs DK，KeSPA Cup A组第二轮。",
    lastSyncedAt: new Date().toISOString(),
  },
  // === LPL Split 3 (7月22日开始，登峰/涅槃组内BO3) ===
  {
    id: "lol-mock-lpl-001",
    game: "lol",
    gameName: "英雄联盟",
    league: "LPL",
    tournament: "LPL Split 3 2026",
    stage: "登峰组 Rumble Stage Week 1 - 深圳NIP主场",
    teamA: "BLG",
    teamB: "TES",
    startTime: futureDate(9, 17),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "LPL Split 3登峰组开幕战，BLG对阵TES。深圳NIP主场。",
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "lol-mock-lpl-002",
    game: "lol",
    gameName: "英雄联盟",
    league: "LPL",
    tournament: "LPL Split 3 2026",
    stage: "登峰组 Rumble Stage Week 1",
    teamA: "JDG",
    teamB: "EDG",
    startTime: futureDate(9, 19),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "JDG迎战EDG，登峰组首周焦点战。",
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "lol-mock-lpl-003",
    game: "lol",
    gameName: "英雄联盟",
    league: "LPL",
    tournament: "LPL Split 3 2026",
    stage: "涅槃组 Rumble Stage Week 1",
    teamA: "WBG",
    teamB: "iG",
    startTime: futureDate(10, 15),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "涅槃组WBG对阵iG，保级关键战。",
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "lol-mock-lpl-004",
    game: "lol",
    gameName: "英雄联盟",
    league: "LPL",
    tournament: "LPL Split 3 2026",
    stage: "登峰组 Rumble Stage Week 1",
    teamA: "AL",
    teamB: "WE",
    startTime: futureDate(10, 17),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "AL对阵WE，登峰组积分争夺。",
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "lol-mock-lpl-005",
    game: "lol",
    gameName: "英雄联盟",
    league: "LPL",
    tournament: "LPL Split 3 2026",
    stage: "涅槃组 Rumble Stage Week 1",
    teamA: "LNG",
    teamB: "NIP",
    startTime: futureDate(11, 17),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "LNG与NIP的涅槃组对决。",
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "lol-mock-lpl-006",
    game: "lol",
    gameName: "英雄联盟",
    league: "LPL",
    tournament: "LPL Split 3 2026",
    stage: "登峰组 Rumble Stage Week 1",
    teamA: "TT",
    teamB: "LGD",
    startTime: futureDate(11, 19),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "TT与LGD的登峰组对决。",
    lastSyncedAt: new Date().toISOString(),
  },
  // === LEC Playoffs (7月22-28日) ===
  {
    id: "lol-mock-lec-001",
    game: "lol",
    gameName: "英雄联盟",
    league: "LEC",
    tournament: "LEC Summer 2026",
    stage: "Playoffs Upper Final",
    teamA: "G2",
    teamB: "FNC",
    startTime: futureDate(9, 17),
    format: "BO5",
    status: "scheduled",
    source: "mock",
    summary: "LEC季后赛胜者组决赛，G2对阵Fnatic。",
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "lol-mock-lec-002",
    game: "lol",
    gameName: "英雄联盟",
    league: "LEC",
    tournament: "LEC Summer 2026",
    stage: "Playoffs Lower Bracket",
    teamA: "KC",
    teamB: "GX",
    startTime: futureDate(10, 17),
    format: "BO5",
    status: "scheduled",
    source: "mock",
    summary: "LEC季后赛败者组，Karmine Corp对阵GiantX。",
    lastSyncedAt: new Date().toISOString(),
  },
  // === LCK Summer 2026 (7月29日恢复，3-4轮) ===
  {
    id: "lol-mock-lck-001",
    game: "lol",
    gameName: "英雄联盟",
    league: "LCK",
    tournament: "LCK Summer 2026",
    stage: "Legend组 Round 3 Week 1",
    teamA: "GEN",
    teamB: "T1",
    startTime: futureDate(16, 16),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "LCK后半程重启，GEN在HomeStand迎战T1。",
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "lol-mock-lck-002",
    game: "lol",
    gameName: "英雄联盟",
    league: "LCK",
    tournament: "LCK Summer 2026",
    stage: "Legend组 Round 3 Week 1",
    teamA: "HLE",
    teamB: "KT",
    startTime: futureDate(16, 18),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "HLE对阵KT，Legend组强强对话。",
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "lol-mock-lck-003",
    game: "lol",
    gameName: "英雄联盟",
    league: "LCK",
    tournament: "LCK Summer 2026",
    stage: "Rise组 Round 3 Week 1",
    teamA: "DRX",
    teamB: "BRO",
    startTime: futureDate(17, 16),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "Rise组DRX对阵BRO。",
    lastSyncedAt: new Date().toISOString(),
  },
  // === LCS Summer (7月27-28日) ===
  {
    id: "lol-mock-lcs-001",
    game: "lol",
    gameName: "英雄联盟",
    league: "LCS",
    tournament: "LCS Summer 2026",
    stage: "Regular Season",
    teamA: "TL",
    teamB: "FLY",
    startTime: futureDate(14, 4),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "LCS夏季赛，Team Liquid对阵FlyQuest。",
    lastSyncedAt: new Date().toISOString(),
  },
  // === 已结束的历史比赛（用于测试过滤逻辑） ===
  {
    id: "lol-mock-past",
    game: "lol",
    gameName: "英雄联盟",
    league: "LPL",
    tournament: "LPL Split 2 2026 Playoffs",
    stage: "Grand Final",
    teamA: "BLG",
    teamB: "TES",
    startTime: pastDate(29),
    format: "BO5",
    status: "finished",
    source: "mock",
    summary: "LPL Split 2决赛，BLG 3-0 TES夺得冠军。",
    lastSyncedAt: new Date().toISOString(),
  },
];

export const mockValorantMatches: Match[] = [
  // === VCT CN Stage 2 已结束，Champions 资格赛/训练赛 ===
  {
    id: "valorant-mock-001",
    game: "valorant",
    gameName: "无畏契约",
    league: "VCT CN",
    tournament: "VCT CN 2026",
    stage: "Champions 资格赛",
    teamA: "EDG",
    teamB: "BLG",
    startTime: futureDate(3, 18),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "EDG对阵BLG，争夺VCT Champions CN赛区名额。",
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "valorant-mock-002",
    game: "valorant",
    gameName: "无畏契约",
    league: "VCT CN",
    tournament: "VCT CN 2026",
    stage: "Champions 资格赛",
    teamA: "FPX",
    teamB: "DRG",
    startTime: futureDate(4, 17),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "FPX与DRG的Champions资格争夺战。",
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "valorant-mock-003",
    game: "valorant",
    gameName: "无畏契约",
    league: "Champions",
    tournament: "VCT Champions 2026",
    stage: "小组赛 Day 1",
    teamA: "EDG",
    teamB: "SEN",
    startTime: futureDate(20, 14),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "VCT Champions开幕战，CN赛区EDG对阵美洲Sentinels。",
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "valorant-mock-004",
    game: "valorant",
    gameName: "无畏契约",
    league: "Champions",
    tournament: "VCT Champions 2026",
    stage: "小组赛 Day 2",
    teamA: "PRX",
    teamB: "FNC",
    startTime: futureDate(21, 15),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "Pacific王者PRX迎战EMEA劲旅FNC。",
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "valorant-mock-005",
    game: "valorant",
    gameName: "无畏契约",
    league: "Champions",
    tournament: "VCT Champions 2026",
    stage: "小组赛 Day 1",
    teamA: "BLG",
    teamB: "DRX",
    startTime: futureDate(20, 17),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "VCT Champions首日，BLG对战DRX。",
    lastSyncedAt: new Date().toISOString(),
  },
  // === VCT Pacific ===
  {
    id: "valorant-mock-006",
    game: "valorant",
    gameName: "无畏契约",
    league: "VCT Pacific",
    tournament: "VCT Pacific 2026",
    stage: "Champions 资格赛",
    teamA: "PRX",
    teamB: "GEN",
    startTime: futureDate(2, 16),
    format: "BO3",
    status: "scheduled",
    source: "mock",
    summary: "Paper Rex对阵GEN.G，VCT Pacific重头戏。",
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "valorant-mock-007",
    game: "valorant",
    gameName: "无畏契约",
    league: "VCT Pacific",
    tournament: "VCT Pacific 2026",
    stage: "Champions 资格赛",
    teamA: "T1",
    teamB: "DRX",
    startTime: futureDate(5, 19),
    format: "BO5",
    status: "scheduled",
    source: "mock",
    summary: "T1与DRX的VCT Pacific名额决胜战。",
    lastSyncedAt: new Date().toISOString(),
  },
  // === 已结束 ===
  {
    id: "valorant-mock-past",
    game: "valorant",
    gameName: "无畏契约",
    league: "VCT CN",
    tournament: "VCT CN Stage 2 2026",
    stage: "决赛",
    teamA: "EDG",
    teamB: "BLG",
    startTime: pastDate(14),
    format: "BO5",
    status: "finished",
    source: "mock",
    summary: "VCT CN Stage 2决赛，EDG战胜BLG夺冠。",
    lastSyncedAt: new Date().toISOString(),
  },
];

// Mock 战队名称映射（简称 ↔ 全称）
export const TEAM_NAME_MAP: Record<string, string> = {
  blg: "BLG",
  bilibili: "BLG",
  "bilibili gaming": "BLG",
  tes: "TES",
  "top esports": "TES",
  edg: "EDG",
  "edward gaming": "EDG",
  jdg: "JDG",
  "jd gaming": "JDG",
  rng: "RNG",
  "royal never give up": "RNG",
  wbg: "WBG",
  "weibo gaming": "WBG",
  we: "WE",
  "team we": "WE",
  al: "AL",
  "anyone's legend": "AL",
  "anyones legend": "AL",
  lng: "LNG",
  "lng esports": "LNG",
  tt: "TT",
  "thundertalk gaming": "TT",
  t1: "T1",
  skt: "T1",
  "skt t1": "T1",
  gen: "GEN",
  "gen.g": "GEN",
  dk: "DK",
  "dplus kia": "DK",
  "dwg kia": "DK",
  kt: "KT",
  "kt rolster": "KT",
  hle: "HLE",
  "hanwha life esports": "HLE",
  drx: "DRX",
  prx: "PRX",
  "paper rex": "PRX",
  fpx: "FPX",
  "funplus phoenix": "FPX",
  drg: "DRG",
  "dragon ranger gaming": "DRG",
  g2: "G2",
  "g2 esports": "G2",
  fnc: "FNC",
  fnatic: "FNC",
  sen: "SEN",
  sentinels: "SEN",
};

// 已知赛事列表
export const KNOWN_LEAGUES = [
  { id: "LPL", name: "LPL（英雄联盟职业联赛）", game: "lol" },
  { id: "LCK", name: "LCK（英雄联盟韩国冠军联赛）", game: "lol" },
  { id: "LEC", name: "LEC（英雄联盟欧洲冠军联赛）", game: "lol" },
  { id: "LCS", name: "LCS（英雄联盟北美冠军联赛）", game: "lol" },
  { id: "MSI", name: "MSI（季中冠军赛）", game: "lol" },
  { id: "Worlds", name: "Worlds / EWC（全球总决赛 / 电竞世界杯）", game: "lol" },
  { id: "VCT CN", name: "VCT CN（无畏契约冠军巡回赛中国赛区）", game: "valorant" },
  { id: "VCT Pacific", name: "VCT Pacific（无畏契约冠军巡回赛太平洋赛区）", game: "valorant" },
  { id: "VCT Americas", name: "VCT Americas（无畏契约冠军巡回赛美洲赛区）", game: "valorant" },
  { id: "VCT EMEA", name: "VCT EMEA（无畏契约冠军巡回赛欧洲赛区）", game: "valorant" },
  { id: "Masters", name: "VCT Masters（无畏契约大师赛）", game: "valorant" },
  { id: "Champions", name: "VCT Champions（无畏契约全球冠军赛）", game: "valorant" },
  { id: "KPL", name: "KPL（王者荣耀职业联赛）", game: "hok" },
  { id: "KCC", name: "KCC（王者荣耀挑战者杯）", game: "hok" },
];

export const KNOWN_GAMES = [
  { id: "lol", name: "英雄联盟" },
  { id: "valorant", name: "无畏契约" },
  { id: "hok", name: "王者荣耀" },
];
